### ISSUE TITLE
problème image sur ici tou.tv 

### ISSUE THREAD

**Issue by KodiTopQuebec** [anisite/plugin.infologique.tou.tv#32]
depuis la mise a jour de inputStream adaptive lorsque l'on écoute du contenu sur ici tou.tv l'image est verte avec pixel
ca fait cela sur boite android , a partir d'un pc je n'ai pas ce problème. 
est ce que un développeur pourrait regarder cela de son coté merci a l'avance

**Comment by erikatremblay** [comment]
Effectivement sa fait cela j’ai une homatics box r 4k plus et j’ai le meme soucis avec Kodi 20.3. 
![IMG_8196](https://github.com/anisite/plugin.infologique.tou.tv/assets/43388286/5cf63deb-c7ef-4fe0-bf25-8e695a74f312)

**Comment by Sphinxroot** [comment]
log file jai ca maintenant  sous leia 18.9   et image floue sous matrix 19.5 portable  win10 pro

2024-02-08 17:48:46.043 T:7416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: Non-ASCII character '\xc3' in file C:\Users\SphinxLaboratory\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\utilities.py on line 46, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (utilities.py, line 46)
                                            Traceback (most recent call last):
                                              File "C:\Users\SphinxLaboratory\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\default.py", line 1, in <module>
                                                ﻿from resources.lib.toutv import Main
                                              File "C:\Users\SphinxLaboratory\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\toutv.py", line 38, in <module>
                                                from . import scraper
                                              File "C:\Users\SphinxLaboratory\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\scraper.py", line 10, in <module>
                                                from .utilities import get_clientKey
                                              File "C:\Users\SphinxLaboratory\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\utilities.py", line 46
                                            SyntaxError: Non-ASCII character '\xc3' in file C:\Users\SphinxLaboratory\AppData\Roaming\Kodi\addons\plugin.infologique.tou.tv\resources\lib\utilities.py on line 46, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
                                            -->End of Python script error report<--
2024-02-08 17:48:46.058 T:3636   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
2024-02-08 17:48:46.075 T:9472   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed

**Comment by KodiTopQuebec** [comment]
toujours rien pour corriger soit inputstream adaptive ou dans ici tou.tv ? lorsque je remplace inputstream par l ancienne version 20.3.14 tout est beau , le problème vient de la nouvelle version 20.3.17

**Comment by anisite** [comment]
ça semble lié à ce problème : https://github.com/xbmc/inputstream.adaptive/issues/1468

**Comment by erikatremblay** [comment]
D’accord, donc il faut faire quoi pour corriger? On doit attendre ?

**Comment by KodiTopQuebec** [comment]
il y a eu une patch de sortie , pour moi fonctionne num 1 , télécharger le .zip et installer le a partir de kodi , voici le lien pour la patch , merci a ce généreux pour avoir travaillé la dessus
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1476/1/artifacts/
