### ISSUE TITLE
Le plugin ne fonctionne plus

### ISSUE THREAD

**Issue by gabtremblay** [anisite/plugin.infologique.tou.tv#5]
Bonjour,

Tou.tv ont procédé à une mise à jour de leur frontend et le plugin ne fonctionne plus. Testé sur un nvidia shield tv et sur un rasberry pi. (kodi 18.1 et 18.2).

**Comment by thibaulf** [comment]
Même chose de mon côté: je sus sur un pi3 avec OSMC (Kodi 18.2). Je me suis retapé un install complet aujourd’hui et le problème subsiste. Heureux de voir que c’est pas juste moi!

**Comment by anisite** [comment]
Connecté ou anonyme ? rien ne s'affiche ou on peut naviguer un peu ?

**Comment by thibaulf** [comment]
Je suis anonyme, Le plugin ne se charge pas (même pas de liste). J'ai ça dans le log : 

> 2019-04-24 19:44:18.428 T:1916159536   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
> 2019-04-24 19:44:20.233 T:1487925984   ERROR: Traceback (most recent call last):
> 2019-04-24 19:44:20.233 T:1487925984   ERROR:   File "/home/osmc/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 358, in _add_directory_root_extra
> 2019-04-24 19:44:20.234 T:1487925984   ERROR:     sections = json.loads(sections)
> 2019-04-24 19:44:20.234 T:1487925984   ERROR:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
> 2019-04-24 19:44:20.235 T:1487925984   ERROR:     return _default_decoder.decode(s)
> 2019-04-24 19:44:20.235 T:1487925984   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
> 2019-04-24 19:44:20.236 T:1487925984   ERROR:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 2019-04-24 19:44:20.236 T:1487925984   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
> 2019-04-24 19:44:20.236 T:1487925984   ERROR:     raise ValueError("No JSON object could be decoded")
> 2019-04-24 19:44:20.236 T:1487925984   ERROR: ValueError: No JSON object could be decoded
> 2019-04-24 19:44:20.236 T:1754260192   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
> 2019-04-24 19:44:20.237 T:1916159536   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed

**Comment by anisite** [comment]
merci, je viens de voir ce qui a été supprimé, j'ai a l'interne une nouvelle version qui devrait mieux fonctionner, j'était en train de la préparer mais je ne peux pas garantir de délai de dispo.

**Comment by zoneamick** [comment]
je me suis permis de mettre a jour les images au gout tu jour si jamais tu as de l’intérêt à les changer.
![icon](https://user-images.githubusercontent.com/11229853/56708386-81f1d200-66ea-11e9-803a-9f4ff0d7d802.png)
![fanart](https://user-images.githubusercontent.com/11229853/56708387-81f1d200-66ea-11e9-87bd-a556405b9c98.jpg)

**Comment by anisite** [comment]
Je regarde comment je vais présenter le menu... pas simple de tout mettre sans trop mêler de choses ...
@zoneamick je vais regarder pour les images

**Comment by anisite** [comment]
Voici une première aperçue de la nouvelle version :
 ![2019-04-25 15_45_18-Kodi](https://user-images.githubusercontent.com/3194288/56763831-464e1b00-6771-11e9-8fcc-53135b88971c.png)

![image](https://user-images.githubusercontent.com/3194288/56763871-6087f900-6771-11e9-8afd-91e11fbc9759.png)

**Comment by gabtremblay** [comment]
Shiny! Très cool.

**Comment by thibaulf** [comment]
Nice !

**Comment by ko570a** [comment]
Où est-elle cette nouvelle version, est-elle disponible?

**Comment by anisite** [comment]
@ko570a elle n'est pas encore déployée, je tente de le faire ce soir avant 20h... Il y a beaucoup de changements d'adresses, heureusement j'avais déjà commencé quelque chose.

**Comment by anisite** [comment]
le plugin a été modifié, il fonctionne seulement avec un compte pour le moment (vous pouvez tester, mais les vidéos ne partent pas je crois... prenez 2 secondes pour en créer un, c'est gratuit!)

l'update va se faire d'ici ... 1 heure, automatiquement!

**Comment by maxmasou** [comment]
Good job! Seul petit problème, j'ai remarqué que les émissions de la journée même ne marche pas. Tout le reste semble marché. La nouvelle interface est vraiment top en passant. Sa me donne le goût de m'abonner à l'extra!l loll

**Comment by anisite** [comment]
@maxmasou quels épisodes au juste, moi ça semble ok?

**Comment by maxmasou** [comment]
Si tu vas disons dans rattrapage télé, aujourd'hui, Le grand rire de ..., PA Methot. Sa ne marche pas! Dans le log sa me dit en gros: 
```
2019-04-25 23:48:02.858 T:140408696850176   ERROR: CCurlFile::Open failed with code 404 for https://toutvuniver-vh.akamaihd.net/i/013/mp4/g/2019-04-25_20_30_00_grandrirede_0038_,500,800,1200,2000,3000,.mp4.c    smil/master.m3u8?hdnea=st=1556250478~exp=1556250598~acl=/i/013/mp4/g/2019-04-25_20_30_00_grandrirede_0038_*~hmac=6ea39ede9de0e35a535f080971a5c6de489c2d10d06a5ecea376a85c24548c32:
313 2019-04-25 23:48:02.858 T:140408696850176  NOTICE: Creating Demuxer
314 2019-04-25 23:48:03.000 T:140408696850176   ERROR: OpenDemuxStream - Error creating demuxer
315 2019-04-25 23:48:03.000 T:140408696850176  NOTICE: CVideoPlayer::OnExit()
316 2019-04-25 23:48:03.013 T:140409007216384   ERROR: EXCEPTION: XBMC is not playing any media file
317 2019-04-25 23:48:03.029 T:140409780675328  NOTICE: CVideoPlayer::CloseFile()
318 2019-04-25 23:48:03.033 T:140409780675328  NOTICE: VideoPlayer: waiting for threads to exit
319 2019-04-25 23:48:03.033 T:140409780675328  NOTICE: VideoPlayer: finished waiting
320 2019-04-25 23:48:03.514 T:140409780675328 WARNING: CGUIMediaWindow::OnMessage - updating in progress
321 2019-04-25 23:48:05.267 T:140408722028288   ERROR: NEWADDON Invalid Date Format "2019-04-25 00:00:00"
322 2019-04-25 23:48:05.285 T:140408722028288   ERROR: NEWADDON Invalid Date Format "2019-04-18 00:00:00"
```

**Comment by anisite** [comment]
@maxmasou es-tu en HLS ou widevine?

**Comment by maxmasou** [comment]
Les 2 ne marche pas. J'ai essayé les 2. Faudrait que j'essaie sur mon Raspberry pour voir si c'est pareil...

**Comment by anisite** [comment]
ok parce que ici ça marche et toi tu as un 404... c'est p-e les comptes extra qui marche, a cause d'un bug... je vais regarder demain! merci!

**Comment by thibaulf** [comment]
J’ai pas mal le même problème de mon côté: les vidéos du jour même marchent pas, mais ok pour les autres. je suis avec un compte. A part de ça l’interface est vraiment cool!

**Comment by anisite** [comment]
Pour les non-abonnés, j'utilisait le code de connexion des téléviseur samsung, c'était plus facile de contourner la protection, mais cette source est maintenant fermée : https://assistance.radio-canada.ca/hc/fr/articles/360016505373-ICI-TOU-TV-D%C3%A9sactivation-d-anciennes-applications

Je me rends compte que pour corriger le problème que certains avaient avec les DRM j'ai forcé l'utilisation de cette source quand le vidéo était sans DRM... donc bref le problème semble venir de là, je vais chercher un autre trou!

**Comment by anisite** [comment]
J'ai lancé la version 4.0.1, inutile de changer les paramètres de type de flux ou drm, celle-ci ne s'en occupe plus, j'ai normalisé la lecture pour tous, donnez-moi le feedback a savoir ce que ça a changé chez vous svp!

**Comment by gabtremblay** [comment]
Ça fonctionne de mon coté. La nouvelle version n'apparait pas dans dépotquebec par contre, j'ai du faire la mise a jour directement avec le zip de la 4.0.1

**Comment by thibaulf** [comment]
@anisite: C'est cool, ça marche de mon coté. Merci pour ton travail

**Comment by ko570a** [comment]
Ça  fonctionne avec version 4.0.0 mais  non avec 4.0.1

**Comment by ko570a** [comment]
Ok ça  fonctionne maintenant.
À part radio canada, les autres sont presque tous pour les abonnés  extra

**Comment by franckgaga** [comment]
Le problème est revenu ce soir. La page principal de l'addiciel ne s'affichait pas du tout. J'ai réussi à faire fonctionner l'addiciel à nouveau en supprimant mon compte des paramètres. La page principale s'est ensuite affichée et je me suis re-connecté là. Voici mon log:

```2019-04-30 18:17:50.457 T:1300231024   DEBUG: StartScript - calling plugin ICI TOU.TV('plugin://plugin.infologique.tou.tv/','19','','resume:false')
2019-04-30 18:17:50.458 T:1277162352   DEBUG: Thread LanguageInvoker start, auto delete: false
2019-04-30 18:17:50.458 T:1277162352    INFO: initializing python engine.
2019-04-30 18:17:50.458 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): start processing
2019-04-30 18:17:50.487 T:1277162352   DEBUG: -->Python Interpreter Initialized<--
2019-04-30 18:17:50.488 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): the source file to load is "/storage/.kodi/addons/plugin.infologique.tou.tv/default.py"
2019-04-30 18:17:50.489 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): setting the Python path to /storage/.kodi/addons/plugin.infologique.tou.tv:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.kodi-six/libs:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2019-04-30 18:17:50.489 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): entering source directory /storage/.kodi/addons/plugin.infologique.tou.tv
2019-04-30 18:17:50.489 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): instantiating addon using automatically obtained id of "plugin.infologique.tou.tv" dependent on version 2.1.0 of the xbmc.python api
2019-04-30 18:17:50.513 T:1937084432   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-04-30 18:17:50.657 T:1277162352   DEBUG: ---------------------PREMIUM CHECK--------------------------------
2019-04-30 18:17:50.658 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting definitions
2019-04-30 18:17:50.658 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: trying to load setting definitions from old format...
2019-04-30 18:17:50.659 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting values
2019-04-30 18:17:50.659 T:1277162352   DEBUG: Continue premium check
2019-04-30 18:17:51.265 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting definitions
2019-04-30 18:17:51.265 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: trying to load setting definitions from old format...
2019-04-30 18:17:51.267 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting values
2019-04-30 18:17:51.302 T:1277162352   DEBUG: GET_HTML
2019-04-30 18:17:51.517 T:1277162352   DEBUG: fail
2019-04-30 18:17:51.524 T:1277162352   ERROR: Traceback (most recent call last):
2019-04-30 18:17:51.524 T:1277162352   ERROR:   File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 367, in _add_directory_root_extra
2019-04-30 18:17:51.526 T:1277162352   ERROR:     sections = json.loads(sections)
2019-04-30 18:17:51.526 T:1277162352   ERROR:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2019-04-30 18:17:51.526 T:1277162352   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2019-04-30 18:17:51.526 T:1277162352   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2019-04-30 18:17:51.526 T:1277162352   ERROR: ValueError: No JSON object could be decoded
2019-04-30 18:17:51.527 T:1300231024   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
2019-04-30 18:17:51.527 T:1277162352    INFO: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
2019-04-30 18:17:51.527 T:1300231024   DEBUG: Thread waiting 1300231024 terminating
2019-04-30 18:17:51.527 T:1937084432   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-04-30 18:17:51.527 T:1277162352   DEBUG: onExecutionDone(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py)
2019-04-30 18:17:51.528 T:1937084432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed
2019-04-30 18:17:51.528 T:1937084432   DEBUG: CGUIMediaWindow::GetDirectory ()
2019-04-30 18:17:51.528 T:1937084432   DEBUG:   ParentPath = [plugin://plugin.infologique.tou.tv/]
2019-04-30 18:17:51.537 T:1300231024   DEBUG: Thread waiting start, auto delete: false
2019-04-30 18:17:51.541 T:1300231024   DEBUG: Thread waiting 1300231024 terminating
2019-04-30 18:17:51.572 T:1300231024   DEBUG: Thread BackgroundLoader start, auto delete: false
2019-04-30 18:17:51.586 T:1300231024   DEBUG: Thread BackgroundLoader 1300231024 terminating
2019-04-30 18:17:51.684 T:1277162352    INFO: Python interpreter stopped
2019-04-30 18:17:51.684 T:1277162352   DEBUG: Thread LanguageInvoker 1277162352 terminating```

**Comment by ko570a** [comment]
Ça fonctionne sur PC avec Kodi 18.3 et version 4.0.2, mais pas sur Android.

**Comment by David675** [comment]
Comment avoir Canal D vrak etc car je peut juste dowloader le dépôt Québec 1.0 ??
