### ISSUE TITLE
Instabilité avec la version 4.0.1

### ISSUE THREAD

**Issue by thibaulf** [anisite/plugin.infologique.tou.tv#6]
Bonjour, le plugin version 4.0.1 semble fonctionner de façon intermittente de mon coté. Ça survient lors de la création de la page d’accueil. C'est weird: ça ressemble au même problème qu'avec 3.0.2, même si tout à changé de ce coté  ...  

Je suis sur OSMC avec Kodi 18 sur un pi3 et je suis connecté avec un compte (gratuit) 

Lorsque ça plante, il suffit souvent d'attendre ou re-essayer pour que se mette à marcher

Dans mon logs
019-04-28 14:00:12.639 T:1541399264   ERROR:   File "/home/osmc/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 367, in _add_directory_root_extra
2019-04-28 14:00:12.777 T:1541399264   ERROR:     sections = json.loads(sections)
2019-04-28 14:00:12.777 T:1541399264   ERROR:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2019-04-28 14:00:12.778 T:1541399264   ERROR:     return _default_decoder.decode(s)
2019-04-28 14:00:12.778 T:1541399264   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2019-04-28 14:00:12.779 T:1541399264   ERROR:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2019-04-28 14:00:12.779 T:1541399264   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2019-04-28 14:00:12.779 T:1541399264   ERROR:     raise ValueError("No JSON object could be decoded")
2019-04-28 14:00:12.779 T:1541399264   ERROR: ValueError: No JSON object could be decoded
2019-04-28 14:00:12.779 T:1549791968   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
2019-04-28 14:00:12.786 T:1915926064   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed

**Comment by franckgaga** [comment]
Il m'arrive parfois la même chose de mon côté sur RPi 3B+ LibreELEC 9.0.1. Connecté à un compte gratuit aussi. J'ai du redémarrer le RPi pour que la page d’accueil du plugin s'affiche.

(très beau look par contre, la version 4.0, good job!)

**Comment by thibaulf** [comment]
Je me suis déconnecté du compte gratuit: so far, ça semble mieux. Pas d'erreurs depuis

**Comment by mbelang** [comment]
J'ai kodi 16 et je ne vois pas l'addon avec la dernière version dans le Repo. J'ai mis le repo a jour pourtant. Est-ce que l'addon est compatible avec kodi 16?

**Comment by anisite** [comment]
Est ce bien le dépôt Québec? Et oui il est possible que l'addon ne se mette pas a jour sur toutes les versions. Tou.tv requiert maintenant une plus grande sécurité pour le décodage des flux vidéo ce que Kodi 16 ne permet pas et la version 17 seulement sur certaines plateforme sois certaines conditions. Seule la 18 est certifiée pour le besoin.

**Comment by mbelang** [comment]
Oui exactement. Je vais mettre Kodi a jour alors

**Comment by franckgaga** [comment]
Pour ma part, je suis resté connecté sur mon compte gratuit et je n'ai pas eu d'erreur à nouveau. Peut-être un bug momentané sur le site de Tou.tv...

**Comment by franckgaga** [comment]
Le problème est revenu ce soir. La page principal de l'addiciel ne s'affichait pas du tout. Pendant que ça plantait, le site de tou.tv fonctionnait bien. J'ai réussi à faire fonctionner l'addiciel à nouveau en supprimant mon compte des paramètres. La page principale s'est ensuite affichée et je me suis re-connecté là. Voici mon log:

```2019-04-30 18:17:50.457 T:1300231024   DEBUG: StartScript - calling plugin ICI TOU.TV('plugin://plugin.infologique.tou.tv/','19','','resume:false')
2019-04-30 18:17:50.458 T:1277162352   DEBUG: Thread LanguageInvoker start, auto delete: false
2019-04-30 18:17:50.458 T:1277162352    INFO: initializing python engine.
2019-04-30 18:17:50.458 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): start processing
2019-04-30 18:17:50.487 T:1277162352   DEBUG: -->Python Interpreter Initialized<--
2019-04-30 18:17:50.488 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): the source file to load is "/storage/.kodi/addons/plugin.infologique.tou.tv/default.py"
2019-04-30 18:17:50.489 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): setting the Python path to /storage/.kodi/addons/plugin.infologique.tou.tv:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.kodi-six/libs:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2019-04-30 18:17:50.489 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): entering source directory /storage/.kodi/addons/plugin.infologique.tou.tv
2019-04-30 18:17:50.489 T:1277162352   DEBUG: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): instantiating addon using automatically obtained id of "plugin.infologique.tou.tv" dependent on version 2.1.0 of the xbmc.python api
2019-04-30 18:17:50.513 T:1937084432   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-04-30 18:17:50.657 T:1277162352   DEBUG: ---------------------PREMIUM CHECK--------------------------------
2019-04-30 18:17:50.658 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting definitions
2019-04-30 18:17:50.658 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: trying to load setting definitions from old format...
2019-04-30 18:17:50.659 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting values
2019-04-30 18:17:50.659 T:1277162352   DEBUG: Continue premium check
2019-04-30 18:17:51.265 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting definitions
2019-04-30 18:17:51.265 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: trying to load setting definitions from old format...
2019-04-30 18:17:51.267 T:1277162352   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting values
2019-04-30 18:17:51.302 T:1277162352   DEBUG: GET_HTML
2019-04-30 18:17:51.517 T:1277162352   DEBUG: fail
2019-04-30 18:17:51.524 T:1277162352   ERROR: Traceback (most recent call last):
2019-04-30 18:17:51.524 T:1277162352   ERROR:   File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 367, in _add_directory_root_extra
2019-04-30 18:17:51.526 T:1277162352   ERROR:     sections = json.loads(sections)
2019-04-30 18:17:51.526 T:1277162352   ERROR:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2019-04-30 18:17:51.526 T:1277162352   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2019-04-30 18:17:51.526 T:1277162352   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2019-04-30 18:17:51.526 T:1277162352   ERROR: ValueError: No JSON object could be decoded
2019-04-30 18:17:51.527 T:1300231024   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
2019-04-30 18:17:51.527 T:1277162352    INFO: CPythonInvoker(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
2019-04-30 18:17:51.527 T:1300231024   DEBUG: Thread waiting 1300231024 terminating
2019-04-30 18:17:51.527 T:1937084432   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-04-30 18:17:51.527 T:1277162352   DEBUG: onExecutionDone(70, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py)
2019-04-30 18:17:51.528 T:1937084432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed
2019-04-30 18:17:51.528 T:1937084432   DEBUG: CGUIMediaWindow::GetDirectory ()
2019-04-30 18:17:51.528 T:1937084432   DEBUG:   ParentPath = [plugin://plugin.infologique.tou.tv/]
2019-04-30 18:17:51.537 T:1300231024   DEBUG: Thread waiting start, auto delete: false
2019-04-30 18:17:51.541 T:1300231024   DEBUG: Thread waiting 1300231024 terminating
2019-04-30 18:17:51.572 T:1300231024   DEBUG: Thread BackgroundLoader start, auto delete: false
2019-04-30 18:17:51.586 T:1300231024   DEBUG: Thread BackgroundLoader 1300231024 terminating
2019-04-30 18:17:51.684 T:1277162352    INFO: Python interpreter stopped
2019-04-30 18:17:51.684 T:1277162352   DEBUG: Thread LanguageInvoker 1277162352 terminating```

**Comment by maxmasou** [comment]
J'ai eu le même bug. J'ai simplement supprimé "watched.db" et "watched_maxmasou@gmail.com.db" dans le dossier ".kodi/userdata/addon_data/plugin.infologique.tou.tv". Tout remarchait après ça... 

Mais finalement le problème revient...
Et la 5 min plus tard sa marche loll...
Weirdo tout ça!

**Comment by maxmasou** [comment]
Même si présentement sa marche, je remarque des erreurs dans le log en navigant dans l'addon.
```
2019-04-30 21:21:18.863 T:139961743517440   ERROR: GetDirectory - Error getting
2019-04-30 21:22:16.174 T:139962037036800   ERROR: Previous line repeats 6 times.
2019-04-30 21:22:16.174 T:139962037036800   ERROR: NEWADDON Unknown Video Info Key "label"
2019-04-30 21:22:18.186 T:139962037036800   ERROR: Previous line repeats 322 times.
2019-04-30 21:22:18.186 T:139962037036800   ERROR: Traceback (most recent call last):
2019-04-30 21:22:18.186 T:139962037036800   ERROR:   File "/home/masou/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 574, in _add_api_url
2019-04-30 21:22:18.187 T:139962037036800   ERROR:     self._add_api_favoris(listitems, Lineup, toutesEmissions)
2019-04-30 21:22:18.188 T:139962037036800   ERROR:   File "/home/masou/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 449, in _add_api_favoris
2019-04-30 21:22:18.188 T:139962037036800   ERROR:     listitem.setThumbnailImage( self.PimpImage(str(item[ "ImageUrl" ]), 360, 202) )
2019-04-30 21:22:18.188 T:139962037036800   ERROR: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 67: ordinal not in range(128)
2019-04-30 21:23:15.750 T:139961500165888   ERROR: NEWADDON Unknown Video Info Key "label"
2019-04-30 21:23:16.248 T:139961500165888   ERROR: Previous line repeats 154 times.
2019-04-30 21:23:16.248 T:139961500165888   ERROR: Traceback (most recent call last):
2019-04-30 21:23:16.248 T:139961500165888   ERROR:   File "/home/masou/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 574, in _add_api_url
2019-04-30 21:23:16.248 T:139961500165888   ERROR:     self._add_api_favoris(listitems, Lineup, toutesEmissions)
2019-04-30 21:23:16.248 T:139961500165888   ERROR:   File "/home/masou/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 449, in _add_api_favoris
2019-04-30 21:23:16.248 T:139961500165888   ERROR:     listitem.setThumbnailImage( self.PimpImage(str(item[ "ImageUrl" ]), 360, 202) )
2019-04-30 21:23:16.248 T:139961500165888   ERROR: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 66: ordinal not in range(128)
2019-04-30 21:23:20.093 T:139961508558592   ERROR: NEWADDON Invalid Date Format "2019-04-28 00:00:00"
2019-04-30 21:23:20.116 T:139961508558592   ERROR: NEWADDON Invalid Date Format "2019-04-21 00:00:00"
2019-04-30 21:23:20.140 T:139961508558592   ERROR: NEWADDON Invalid Date Format "2019-04-14 00:00:00"
2019-04-30 21:23:20.145 T:139961508558592   ERROR: NEWADDON Invalid Date Format "2019-04-07 00:00:00"
```

**Comment by thibaulf** [comment]
@maxmasou : tu est connecté ou pas? Pour une raison que j’ignore, c’est un sans faute depuis deux jours depuis que je me suis déconnecté. Je sais bien que pour les extra il faut l’être, mais ça donne de l’info quand même...

**Comment by anisite** [comment]
je vais ajouter des traces, il semble que les serveurs tou.tv sont pas toujours stables... mais certains kodi sont aussi un peu plus précoce a fermer les connexions http. moi je suis connecté et tout va bien depuis le jour 1 de la nouvelle version et le bout de code qui semble affecter pas mal de monde est le même qu'on soit anonyme, extra ou connecté... étrange!

**Comment by anisite** [comment]
il est sur aussi que d'utiliser l'application en anonyme ça enlève 95% des bénéfices de cette plateforme là. genre ce qui a été écouter ou non et autres...

**Comment by thibaulf** [comment]
En effet! Lorsque je pense à stabilité, il ne me vient pas immédiatement en tête les serveurs de tou.tv .. !

**Comment by maxmasou** [comment]
@thibaulf Je suis connecté. Il y a peut une différence si on utilise Linux ou Windows au niveau des connections au serveur. Je parle pour parler là. Moi j'utilise Debian Buster et OSMC (qui est basé sur Debian Stretch)...

**Comment by thibaulf** [comment]
j’aurais du fermer ma gueule! ça vient de faire l’erreur même sans connexion...

**Comment by maxmasou** [comment]
moi sa marche loll

**Comment by anisite** [comment]
@tibaulf qui est votre fournisseur internet?

**Comment by thibaulf** [comment]
> @tibaulf qui est votre fournisseur internet?

Vidéotron

**Comment by anisite** [comment]
Je vais ajouter des traces ce soir si j'ai 2 min. On pourra savoir...

**Comment by thibaulf** [comment]
> Je vais ajouter des traces ce soir si j'ai 2 min. On pourra savoir...
Super, merci pour ton travail

**Comment by franckgaga** [comment]
Premièrement, bug mineur : j'ai remarqué que l'addiciel plante systématiquement quand on clique sur les en-têtes des dossiers eg: « * / Mes favoris » dans mes favoris, « * / Mes visionnements » dans mes visionnements ou « * / Émssions » dans émmissions.

Deuximement, voici mon log, avec la version 4.0.2 qui contient des traces :
```2019-05-02 20:51:17.108 T:1937453072   DEBUG: HandleKey: 254 (0xfe, obc1) pressed, action is RunAddon(plugin.infologique.tou.tv)
2019-05-02 20:51:17.109 T:1937453072   DEBUG: Activating window ID: 10025
2019-05-02 20:51:17.431 T:1937453072   DEBUG: ------ Window Deinit (MyVideoNav.xml) ------
2019-05-02 20:51:17.431 T:1937453072   DEBUG: FreeVisualisation() done
2019-05-02 20:51:17.441 T:1937453072   DEBUG: Clearing cached fileitems [plugin://plugin.infologique.tou.tv/]
2019-05-02 20:51:17.451 T:1369490288   DEBUG: Thread waiting start, auto delete: false
2019-05-02 20:51:17.454 T:1369490288   DEBUG: Thread waiting 1369490288 terminating
2019-05-02 20:51:17.455 T:1937453072   DEBUG: ------ Window Init (MyVideoNav.xml) ------
2019-05-02 20:51:17.470 T:1937453072   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-05-02 20:51:17.475 T:1937453072   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.infologique.tou.tv/)
2019-05-02 20:51:17.475 T:1937453072   DEBUG:   ParentPath = [plugin://plugin.infologique.tou.tv/]
2019-05-02 20:51:17.477 T:1369490288   DEBUG: Thread waiting start, auto delete: false
2019-05-02 20:51:17.493 T:1790935920   DEBUG: CAddonDatabase::SetLastUsed[plugin.infologique.tou.tv] took 18 ms
2019-05-02 20:51:17.494 T:1361097584   DEBUG: onExecutionDone(8, /storage/.kodi/addons/plugin.video.netflix/addon.py)
2019-05-02 20:51:17.494 T:1369490288   DEBUG: StartScript - calling plugin ICI TOU.TV('plugin://plugin.infologique.tou.tv/','3','','resume:false')
2019-05-02 20:51:17.495 T:1352704880   DEBUG: Thread LanguageInvoker start, auto delete: false
2019-05-02 20:51:17.495 T:1352704880    INFO: initializing python engine.
2019-05-02 20:51:17.495 T:1352704880   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): start processing
2019-05-02 20:51:17.577 T:1937453072   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-05-02 20:51:17.688 T:1361097584 WARNING: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.netflix/addon.py): the python script "/storage/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2019-05-02 20:51:17.688 T:1361097584    INFO: Python interpreter stopped
2019-05-02 20:51:17.688 T:1361097584   DEBUG: Thread LanguageInvoker 1361097584 terminating
2019-05-02 20:51:17.722 T:1352704880   DEBUG: -->Python Interpreter Initialized<--
2019-05-02 20:51:17.722 T:1352704880   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): the source file to load is "/storage/.kodi/addons/plugin.infologique.tou.tv/default.py"
2019-05-02 20:51:17.725 T:1352704880   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): setting the Python path to /storage/.kodi/addons/plugin.infologique.tou.tv:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.kodi-six/libs:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2019-05-02 20:51:17.725 T:1352704880   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): entering source directory /storage/.kodi/addons/plugin.infologique.tou.tv
2019-05-02 20:51:17.739 T:1352704880   DEBUG: CPythonInvoker(9, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): instantiating addon using automatically obtained id of "plugin.infologique.tou.tv" dependent on version 2.1.0 of the xbmc.python api
2019-05-02 20:51:17.969 T:1352704880   DEBUG: ---------------------PREMIUM CHECK--------------------------------
2019-05-02 20:51:17.969 T:1352704880   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting definitions
2019-05-02 20:51:17.970 T:1352704880   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: trying to load setting definitions from old format...
2019-05-02 20:51:17.970 T:1352704880   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting values
2019-05-02 20:51:17.971 T:1352704880   DEBUG: Continue premium check
2019-05-02 20:51:18.565 T:1352704880   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting definitions
2019-05-02 20:51:18.565 T:1352704880   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: trying to load setting definitions from old format...
2019-05-02 20:51:18.565 T:1352704880   DEBUG: CAddonSettings[plugin.infologique.tou.tv]: loading setting values
2019-05-02 20:51:18.567 T:1352704880   DEBUG: GET_HTML
2019-05-02 20:51:18.813 T:1352704880   DEBUG: fail
2019-05-02 20:51:18.824 T:1352704880   DEBUG: ----------DEBUG---------
2019-05-02 20:51:18.828 T:1352704880   ERROR: Traceback (most recent call last):
2019-05-02 20:51:18.829 T:1352704880   ERROR:   File "/storage/.kodi/addons/plugin.infologique.tou.tv/resources/lib/toutv.py", line 324, in _add_directory_root_extra
2019-05-02 20:51:18.835 T:1352704880   ERROR:     sections = json.loads(sections)
2019-05-02 20:51:18.835 T:1352704880   ERROR:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2019-05-02 20:51:18.836 T:1352704880   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2019-05-02 20:51:18.836 T:1352704880   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2019-05-02 20:51:18.836 T:1352704880   ERROR: ValueError: No JSON object could be decoded
2019-05-02 20:51:18.837 T:1369490288   ERROR: GetDirectory - Error getting plugin://plugin.infologique.tou.tv/
2019-05-02 20:51:18.837 T:1369490288   DEBUG: Thread waiting 1369490288 terminating
2019-05-02 20:51:18.838 T:1352704880    INFO: CPythonInvoker(9, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py): script successfully run
2019-05-02 20:51:18.838 T:1352704880   DEBUG: onExecutionDone(9, /storage/.kodi/addons/plugin.infologique.tou.tv/default.py)
2019-05-02 20:51:18.840 T:1937453072   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-05-02 20:51:18.842 T:1937453072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.infologique.tou.tv/) failed
2019-05-02 20:51:18.843 T:1937453072   DEBUG: CGUIMediaWindow::GetDirectory ()
2019-05-02 20:51:18.843 T:1937453072   DEBUG:   ParentPath = [plugin://plugin.infologique.tou.tv/]
2019-05-02 20:51:18.864 T:1369490288   DEBUG: Thread waiting start, auto delete: false
2019-05-02 20:51:18.873 T:1369490288   DEBUG: Thread waiting 1369490288 terminating
2019-05-02 20:51:18.941 T:1369490288   DEBUG: Thread BackgroundLoader start, auto delete: false
2019-05-02 20:51:18.954 T:1369490288   DEBUG: Thread BackgroundLoader 1369490288 terminating
2019-05-02 20:51:19.109 T:1352704880    INFO: Python interpreter stopped
2019-05-02 20:51:19.109 T:1352704880   DEBUG: Thread LanguageInvoker 1352704880 terminating

**Comment by anisite** [comment]
J'ai livré effectivement la version 4.0.2 hier, je viens de livrer la 4.0.3 avec d'autres changements pour le plantage du menu principale. les autres bugs sur le clique du nom de l'élément du haut je ne suis pas sur si je vais mettre des efforts dessus.

**Comment by ko570a** [comment]
Pour ma part, ça fonctionne sur PC avec Kodi 18.3 et version 4.0.2, mais pas sur Android.

**Comment by anisite** [comment]
> Pour ma part, ça fonctionne sur PC avec Kodi 18.3 et version 4.0.2, mais pas sur Android.

@ko570a il va falloir me donner plus de détails, parce que android ça compte des milliers d'appareils et plusieurs versions d'os... donnez moi la version android (6,7,8,9...), le nom de l'appareil, la version de kodi, et autres infos pertinentes...

**Comment by ko570a** [comment]
Version 8.1 nougat , tablette samsung tab A, kodi 18.3. L'image apparaît mais est verte et toute déformée et j'ai le son. À  noter que ça  arrive que sur "Ici tout.tv dans kodi et non sur TVA et non plus sur Noovo.

**Comment by anisite** [comment]
@ko570a est-ce que son bootloader a été unlocké ou est-elle rooté ou modifiée ?

**Comment by ko570a** [comment]
Non, pas modifié, ni rooté. Hier rien n'apparaissait. Aujourd'hui j'ai enlevé mon logging,(mot de passe) et ça ouvre mais toujours le même problème, image verte et déformée avec son. Je vais essayer de désinstaller l'application tout.tv et la réinstaller pour voir s'il y a une différence.

**Comment by ko570a** [comment]
J'ai enlevé Ici tou.tv et réinstaller et même chose.

**Comment by anisite** [comment]
J'ai testé avec 3 appareils android, il me reste ma tablette a tester, mais as tu bien eu tous ces menus ?

![image](https://user-images.githubusercontent.com/3194288/57169994-fa861c00-6dd7-11e9-9b10-5f511ca085d0.png)
![image](https://user-images.githubusercontent.com/3194288/57170000-0671de00-6dd8-11e9-8ed9-1537696bb7e2.png)
![image](https://user-images.githubusercontent.com/3194288/57170009-0ffb4600-6dd8-11e9-8a1f-5ba725de4fed.png)

Android est normalement le plus facile à supporter en widevine... le DRM que j'ai pris pour tou.tv... il n'y as pas 1000 options si ça ne marche pas ... c'est p-e l'installation de kodi qui pose problème... mais bon. je me demande si tu peux me fournir le log ou prendre une capture écran de celui-ci apres avoir reproduit le problème?

**Comment by ko570a** [comment]
Oui, j'ai tout ça...inputstream adaptive et tous les autres aussi...inputstream helper, kodi Six, etc.

**Comment by ko570a** [comment]
J'ai retourné à la version 4.0.0 et ça a marché (image ok), mais j'ai voulu voir si ça  remarcherait avec la dernière version mais non (image déformée ). J'ai donc retourné à  la version 4.0.0 mais ça fonctionnait une fois sur 5 et à la fin ça ne fonctionnait plus. Donc rien à  faire. Merci anisite pour ton travail. Je vais quand même refaire d'autres tests plus tard.

**Comment by mbelang** [comment]
Ok je viens d'updater a kodi 18.x et je peux maintenant installer. Seul detail, j'ai kodi sur un PI3. Quand je veux écouter un émission ça me dit que `widevine` doit etre installé et que ça requiert au moin 2GB d'espace. Est-ce que quelqu'un ici a fait fonctionner sur un PI. J'ose pas cliquer installer pour pas avoir a refaire mon setup...

**Comment by thibaulf** [comment]
@mbelang , j’ai un pi3 et ça marche bien. Tu as pas vraiment le choix d’installer widevine:c’est obligatoire maintenant pour la gestion des DRM

**Comment by mbelang** [comment]
Comment as tu installé? Peut être que ça me prendrait une plus grosse sd card!

**Comment by thibaulf** [comment]
Je l’ai laissé faire, mais oui ça prend de la place pour l’extraction

Le lun. 6 mai 2019 à 22:38, Maxime Belanger <notifications@github.com> a
écrit :

**Comment by franckgaga** [comment]
Follow-up : j'ai utilisé tou.tv plusieurs fois dans les dernier jour et plus aucun bug depuis la dernière version (connecté sur compte gratuit).

Merci beaucoup pour ton travail @anisite !

**Comment by thibaulf** [comment]
Ça marche très bien pour moi aussi et belle job @anisite !

**Comment by ko570a** [comment]
Maintenant, sur PC, la version 4.0.3 qui fonctionnait, ne fonctionne plus pour moi. Je vois tout dans l'addiciel tou.tv mais quand je clique sur une émission pour l'ouvrir, elle n'ouvre pas. L'image s'assombrit une fraction de seconde et rien ne se passe. J'ai donc essayé les autres versions en descendant et celle qui fonctionne pour moi est la version 4.0.0. C'est la seule version qui fonctionne et encore peut-être que demain elle ne fonctionnera plus. Pourquoi la dernière version ne fonctionne pas??

**Comment by ko570a** [comment]
ok, une minute plus tard, ça ne fonctionne plus avec version 4.0.0. Je remets le tout à la version 4.0.3 et ça ne fonctionne pas plus. Pourtant, tous mes autres addiciels fonctionnent à merveille. Il n'y a que tou.tv qui me donne du fil à retordre. Devrais-je enlever Kodi et tout remettre....c'est une bonne job à faire, beaucoup de temps. Y a t'il autre chose que je peux faire?

**Comment by ko570a** [comment]
Voici un imprime écran de mon log :+1: @anisite 
![2019-05-16 23_30_10-Kodi](https://user-images.githubusercontent.com/15527756/57949599-dedc4480-78b2-11e9-9772-9c1c76347f36.jpg)


J'ai retourné à la version 17.4 de Kodi mais rien à faire, ça ne fonctionne pas plus.

**Comment by maxmasou** [comment]
@ko570a Tu dois fournir le log complet parce que la tu fournis seulement 10 lignes sur un log qui doit en contenir 350. (%APPDATA%\Kodi\kodi.log pour les PC Windows selon le wiki de kodi).

**Comment by ko570a** [comment]
J'ai réinstallé Kodi 18.2 Leia et j'ai réessayé tou.tv et ne fonctionne pas. Voici mon log ...au complet.
[kodi.log](https://github.com/anisite/plugin.infologique.tou.tv/files/3194300/kodi.log)
J'ai  mis widevine dans le type de flux dans tou.tv. et j'ai inputstream adaptive activé.

**Comment by maxmasou** [comment]
`ERROR: ADDON: Could not locate inputstream.adaptive.dll`
Moi je dirait d'aller télécharger le zip de inputstream.adaptive sur https://github.com/peak3d/inputstream.adaptive  et de réinstaller inputstream.adaptive dans kodi. 
Changer de version de Kodi régulièrement, surtout vers une version inférieure, est déconseillé. Sa peut corrompre la base de donnée et aussi désactiver certaine extensions essentiels.

Mais dans ton cas le BUG vient fort probablement de inputstream.adaptive.

**Comment by anisite** [comment]
Quelqu'un d'autre ici a réussi sur Windws 7 à le faire fonctionner ? Aussi, j'ai déjà eu un problème similaire et il y a vraiment fallu que je désinstalle Kodi au complet et que je le réinstalle, pas simplement installer par dessus. Je ne sais pas si ça peut t'aider... l'erreur parle effectivement du DLL adaptive absent.

**Comment by anisite** [comment]
Aussi, assure-toi que lors de l'installation tu coche vraiment adaptive pour l'installer.

**Comment by ko570a** [comment]
Merci anisite et maxmasou, je vais essayer la première solution, si ça ne marche pas, j'enlève kodi et je réinstalle en neuf.
Merci!

**Comment by ko570a** [comment]
J'ai essayé d'installer inputstream.adaptive-master.zip mais dans le log, ça me dit: 
"2019-05-18 22:25:30.677 T:10560   ERROR: Failed to read 'zip://E%3a%5cClaude%5cDocuments%5cT%c3%a9l%c3%a9chargements%5cinputstream.adaptive-master.zip/inputstream.adaptive-master/addon.xml'

**Comment by ko570a** [comment]
Ça marche!!!!! enfin. J'ai désinstallé inputstream.adaptive et j'ai réinstallé inputstream.adaptive 2.3.17 et enfin ça fonctionne depuis le temps que je taponne là-dsus. Reste plus qu'à vérifier kodi sur android maintenant. 
C'est le fun d'avoir de l'aide. À plusieurs, on en vient à bout.
Un super merci @anisite @maxmasou

**Comment by anisite** [comment]
merci je ferme le billet!
